// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHC4-i6AD2I1yLw_USnRdgHTcNeRrKlZ4',
    appId: '1:372795707141:web:5bac260ef27e86bdd6316c',
    messagingSenderId: '372795707141',
    projectId: 'login-da453',
    authDomain: 'login-da453.firebaseapp.com',
    storageBucket: 'login-da453.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0tjIb_CpKhZH0s5w3Tuipd7zSU4kM8c',
    appId: '1:372795707141:android:4e3e63be5b814540d6316c',
    messagingSenderId: '372795707141',
    projectId: 'login-da453',
    storageBucket: 'login-da453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS67oZJzwycY-aKlkCozfNAP0oakvUIJ8',
    appId: '1:372795707141:ios:75ba09ade4a874a0d6316c',
    messagingSenderId: '372795707141',
    projectId: 'login-da453',
    storageBucket: 'login-da453.appspot.com',
    iosClientId: '372795707141-pvso67htr3jfehpqn8uigbhff4v5rmfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.persebayaSelamanya',
  );
}
